"""Contains `generate_range_string` function"""

from typing import Iterable


def generate_range_string(numbers: Iterable[int], check_gaps: bool = False):
    """
    *** GENERATED BY CHATGPT ***

    Generates a range string based on an iterable of numbers.

    The function takes an iterable of numbers, converts it to a list, and generates
    a string representation of the ranges within the list. Consecutive numbers
    are represented as a range using a hyphen separator, while non-consecutive
    numbers are treated as individual values.

    Args:
        numbers (Iterable): An iterable of numbers. Will be converted to a list.
        check_gaps(bool): Flag for checking gaps in `numbers`. If True, will check `numbers` against range from min to max of `numbers` and return tuple(range string for `numbers`, range string for gaps in `numbers`)

    Returns:
        str: A string representation of the ranges within the list.
        tuple(str): String representation of ranges, string representation of gaps

    Example::
        numbers = [1, 2, 3, 4, 5, 7, 8, 9, 12, 13, 14, 15]
        range_string = generate_range_string(numbers)
        print(range_string)  # Output: "1-5, 7-9, 12-15"
        range_string = generate_range_string(numbers, check_gaps=True)
        print(range_string)  # Output: ("1-5, 7-9, 12-15", "6, 10-11")
    """
    numbers = sorted(numbers)
    ranges = []  # List to store the start and end values of each range
    if numbers:
        gaps = [i for i in range(min(numbers), max(numbers)) if i not in numbers]
    else:
        gaps = []
    start = None  # Variable to track the start value of a range

    # Iterate over the numbers
    for num in numbers:
        if start is None:
            start = num
        elif num != numbers[numbers.index(num) - 1] + 1:
            # Non-consecutive number encountered, add range to the list
            ranges.append((start, numbers[numbers.index(num) - 1]))
            start = num

    # Check if there is a pending range and add it to the list
    if start is not None:
        ranges.append((start, numbers[-1]))

    # Returns the range string by formatting the range list
    range_string = ", ".join(
        [str(start) if start == end else f"{start}-{end}" for start, end in ranges]
    )
    if check_gaps:
        return (
            range_string,
            generate_range_string(gaps, False),
        )
    else:
        return range_string
